apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx:{{ .Values.tag }}
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
         - name: nginx-index
           mountPath: /usr/share/nginx/html/
      restartPolicy: Always
      volumes:
       - name: nginx-index
         configMap:
           name: nginx-index
           items:
           - key: index.html
             path: index.html
