apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to GCPUG!</title>
    <style>
        body {
            width: 35em;
            margin: 0 auto;
            font-family: Tahoma, Verdana, Arial, sans-serif;
        }
    </style>
    </head>
    <body>
    <h1>Welcome to GCPUG!</h1>
    <p>If you see this page, the GCPUG web server is successfully installed and
    working. Further configuration is required.</p>

    <p>For online documentation and support please refer to
    <a href="http://meetup.com/gcpugsg">meetup.com</a>.
    <p><em>Thank you for joining GCPUG.</em></p>
    </body>
    </html>
